[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]

[profile.release]
opt-level = 3
debug = false
strip = true
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "unwind"
codegen-units = 1
